---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- name: Ensure exim is installed.
  package: "name={{ exim_package }} state=present"
- name: Ensure exim4-daemon-heavy is installed.
  package: "name=exim4-daemon-heavy state=present"
- name: Configure exim (Debian only).
  lineinfile:
    dest: "{{ exim_configuration_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: '^dc_eximconfig_configtype'
      line: "dc_eximconfig_configtype='{{ exim_dc_eximconfig_configtype }}'"
    - regexp: '^dc_localdelivery'
      line: "dc_localdelivery='{{ exim_dc_localdelivery }}'"
    - regexp: '^dc_other_hostnames'
      line: "dc_other_hostnames='{{ dc_other_hostnames }}'"
    - regexp: '^dc_relay_domains'
      line: "dc_relay_domains='{{ dc_relay_domains }}'"
    - regexp: '^dc_local_interfaces'
      line: "dc_local_interfaces='{{ dc_local_interfaces }}'"
    - regexp: '^dc_use_split_config'
      line: "dc_use_split_config='{{ dc_use_split_config }}'"
  notify: restart exim
  when: ansible_os_family == 'Debian'

- name: Configure primary_hostname (if set).
  lineinfile:
    dest: "{{ exim_configuration_file }}"
    regexp: '^#?\s?primary_hostname'
    line: "primary_hostname={{ exim_primary_hostname }}"
    state: present
  notify: restart exim
  when: exim_primary_hostname is defined and exim_primary_hostname

- name: Ensure exim is running.
  service: "name={{ exim_daemon }} state=started enabled=yes"
